blank_issues_enabled: false
contact_links:
    -   name: Support Questions & Other
        url: {{repository_url}}/discussions
        about: Discuss any issues related to the application or templates working with it.
