name: phpunit
on: [ push ]

jobs:
    build:
        runs-on: ubuntu-20.04

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.2" ]

        name: PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, bcmath
                    coverage: none

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: sudo vendor/bin/phpunit
